#!/usr/bin/env bash
# Script that configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
str1="\n\tadd_header X-Served-By \$HOSTNAME;"
str2="\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sed -i "s/server_name _;/$str$str1$str2/" /etc/nginx/sites-enabled/default
service nginx start