#!/usr/bin/env bash
# Bash script configures a new Ubuntu machine to match the task requirements
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/cus_404.html
str="server_name _;\n\trewrite ^\/redirect_me twitter.com permanent;"
str1="\n\tadd_header X-Served-By \$hostname;"
str2="\n\terror_page 404 \/cus_404.html;\n\tlocation = \/cus_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"

sed -i "s/server_name _;/$str$str1$str2/" /etc/nginx/sites-enabled/default
service nginx start