#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with requirements
cp /etc/hosts ~/hosts.ne
sed -ie "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts